### ISSUE TITLE
Removing after reading issue!

### ISSUE THREAD

**Issue by CyberSecAlexG** [MushroomMif/aoh3-fabric-loader#1]
Hey Mushroom, I started a discord community around your Fabric mod loader release for AoH3. I want to inspire people to learning Fabric for making mods, and I want to invite you to become a part of the community as it grows. Any role, I'm happy to give to you, and it would be awesome to have you onboard.
https://discord.gg/4UReH6aQZm

I'll be learning how to use the API myself, but I wanted a place for people to share their creations, suggestions, and get help during mod development. If you join the server, I'm happy to add you on Discord and figure out what we can do. I didn't know how else to contact you other than through Github issues, or Reddit.

**Comment by MushroomMif** [comment]
Oh, that's really cool! I also thought about creating a discord server for Fabric AOH3 but haven't gotten to it. 
And thank you for your interest in this project
